# nom du job: arbitraire
test:
  tags:
    - formation
  # image du job: pour exécuter du python
  image: python:3.14.4-slim-trixie
  # commandes préparatoires: installation des dépendances dans un venv
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r app/requirements.txt
    - pip install -r app/requirements-dev.txt
  script:
    - cd app/
    - pytest -m "not e2e"