# image par défaut du pipeline, peut être surchargée par l'image des jobs
image: python:${CICD_IMAGE_TAG}

variables:
  CICD_IMAGE_TAG: 3.14.4-slim-trixie
  # en gitlab les valeurs d'environnement ne sont que des chaînes de caractèress
  TRIGGER_CACHE: "off"

stages:
  - installing
  - testing

generate deps:
  tags:
    - formation
  stage: installing
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r app/requirements.txt
    - pip install -r app/requirements-dev.txt
  cache:
    key: cache-deps-${CI_COMMIT_BRANCH}
    paths:
      - venv/
    policy: push
  rules:
    - changes:
        - app/requirements.txt
        - app/requirements-dev.txt
    # règle manuelle pour forcer la génération des dépendances
    # opérateur possibles : ==, !=, (regex: =~, !~)
    - if: $TRIGGER_CACHE == "on"


test:
  tags:
    - formation
  stage: testing
  script:
    - source venv/bin/activate
    - cd app/
    - pytest -m "not e2e"
  cache:
    key: cache-deps-${CI_COMMIT_BRANCH}
    policy: pull
    untracked: true