image: ${CI_REGISTRY_IMAGE}/python:${CICD_IMAGE_TAG}

variables:
  CICD_IMAGE_TAG: 3.14.4-slim-trixie
  TRIGGER_CACHE: "off"

stages:
  - installing
  - testing

generate deps:
  tags:
    - formation
  stage: installing
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r app/requirements.txt
    - pip install -r app/requirements-dev.txt
  cache:
    key: cache-deps-${CI_COMMIT_BRANCH}
    paths:
      - venv/
    policy: push
  rules:
    - changes:
        - app/requirements.txt
        - app/requirements-dev.txt
    - if: $TRIGGER_CACHE == "on"


test:
  tags:
    - formation
  stage: testing
  script:
    - source venv/bin/activate
    - cd app/
    # ">" : permet de convertir les sauts de ligne en espace
    - >
      pytest -m "not e2e" 
      --junit-xml=reports/junit.xml
  cache:
    key: cache-deps-${CI_COMMIT_BRANCH}
    policy: pull
    untracked: true
  artifacts:
    when: always
    access: all
    expire_in: 1 hour
    paths:
      - app/reports/junit.xml
    # rapports spéciaux liés à des formats et technos attendus par Gitlab
    # pour incrustation dans la GUI
    reports:
      junit: app/reports/junit.xml